Revert r13673 - test suite regression
{{{
===============================================================================
[ERROR]: xquotient.test.test_qpeople.AddPersonTestCase.test_addPerson

Traceback (most recent call last):
  File "/home/divmod/q-linux/q-linux/build/Quotient/xquotient/test/test_qpeople.py", line 27, in test_addPerson
    person = addPersonFrag.addPerson(
  File "/home/divmod/q-linux/q-linux/build/Mantissa/xmantissa/people.py", line 1359, in addPerson
    self.store.transact(
  File "/home/divmod/q-linux/q-linux/build/Axiom/axiom/store.py", line 1659, in transact
    result = f(*a, **k)
  File "/home/divmod/q-linux/q-linux/build/Quotient/xquotient/qpeople.py", line 55, in _addPerson
    person = people.AddPersonFragment._addPerson(self, *a, **kw)
  File "/home/divmod/q-linux/q-linux/build/Mantissa/xmantissa/people.py", line 1335, in _addPerson
    for create in submission.create:
exceptions.AttributeError: list object has no attribute create
===============================================================================
}}}